import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { config } from '../omdb-app/app-config'
import { GetMoviesByTitle } from '../omdb-app/GetMoviesByTitle'
import React from 'react'

const Home: NextPage = () => {
  const [searchText, setSearchText] = React.useState<string | null>(null);
  const inputRef = React.useRef<HTMLInputElement>(null)

  const handleSearchTerm = (event: React.ChangeEvent<HTMLInputElement>) => {
    setSearchText(event.target.value)
  }

  const handleReset = () => {
    setSearchText(null)
  }

  console.log(searchText)

  return (
    <div className={styles.container}>
      <Head>
        <title>{config.head.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={config.head.favicon} />
      </Head>

      <main className={styles.main}>
        <label>Search Movies by Title</label>
        <input
          type="text"
          name="movie-title"
          value={searchText ? searchText : ""}
          onChange={(event) => handleSearchTerm(event)}
        />
        <input
          type="reset"
          defaultValue="Reset"
          value="Clear"
          onClick={handleReset}
        />
        <div>Now searching for ... {searchText}</div>

        {/* Null Safety */}
        {searchText && <GetMoviesByTitle searchText={searchText} />}
      </main>

      <footer className={styles.footer}>
        <p>{config.footer.text}</p>
      </footer>
    </div>
  )
}

export default Home
