import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { config } from '../omdb-app/app-config'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{config.head.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={config.head.favicon} />
      </Head>

      <main className={styles.main}>
        everything major goes in here !!!
      </main>

      <footer className={styles.footer}>
        <p>{config.footer.text}</p>
      </footer>
    </div>
  )
}

export default Home
