import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { config } from '../omdb-app/app-config'
import { GetMoviesByTitle } from '../omdb-app/GetMoviesByTitle'
import React from 'react'
import { useLocalStorage } from 'react-use'

const Home: NextPage = () => {
  const [searchText, setSearchText] = React.useState<string | null>(null);
  const [searches, setSearches, remove] = useLocalStorage('search-history', '')

  const handleSearchTerm = (event: React.ChangeEvent<HTMLInputElement>) => {
    setSearchText(event.target.value)
    setSearches(event.target.value)
  }

  const handleReset = () => {
    setSearchText(null)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>{config.head.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={config.head.favicon} />
      </Head>

      <main className={styles.main}>
        <div className={styles.card}>
          <h3>Search By Title</h3>
          <label>Enter movie title</label>
          <input
            type="text"
            name="movie-title"
            value={searchText ? searchText : ""}
            onChange={(event) => handleSearchTerm(event)}
          />
          <input
            type="reset"
            value="Clear"
            onClick={handleReset}
          />
        </div>

        {/* Null Safety */}
        {searchText && <GetMoviesByTitle searchText={searchText} />}
      </main >

      <footer className={styles.footer}>
        <p>{config.footer.text}</p>
      </footer>
    </div >
  )
}

export default Home
